### ISSUE TITLE
Feature request: restaurants to add

### ISSUE THREAD

**Issue by bumerankkk** [slidinGuy/lunchbot-pq#7]
http://www.laudon-nj.cz/denni-menu.php
https://www.facebook.com/pg/Spaghetteria-Mamma-Mia-523252117862585/posts/?ref=page_internal

**Comment by Looda** [comment]
"Laudon" definition and parser added.

**Comment by slidinGuy** [comment]
Mama-mia working as well. Thanks @Looda
