### ISSUE TITLE
Keyword to invoke lunchbot should be ignored if they are used in a sentence

### ISSUE THREAD

**Issue by bumerankkk** [slidinGuy/lunchbot-pq#9]
For example sentence with emoji like:
"Who is in :jicin" office?" would trigger **lunchbot** unintendedly.

**Comment by Looda** [comment]
Could be done **slack** way, as command `/lunch ostrava` `/lunch basta kovork` or `/lunch jicin`.
May be with support for `:name:` to keep emoji there

**Comment by Looda** [comment]
Should be implemented now. command is `!lunch` or bot name `@lunchbot`

**Comment by slidinGuy** [comment]
Fixed in #12
